metaphor:
  image:
    repository: ghcr.io/moabukar-dev/metaphor
  imagePullSecrets:
    - name: docker-config
  ingress:
    enabled: true
    className: ''
    hosts:
      - host: metaphor-staging.kubefirst.dev
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: metaphor-staging-tls
        hosts:
          - metaphor-staging.kubefirst.dev
  metaphor:
    host: https://metaphor-staging.kubefirst.dev/api
    console: https://kubefirst.kubefirst.dev
  vaultMountPoint: kubefirst
  vaultSecretPath: staging/metaphor
