apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apache
  namespace: argocd
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
  # annotations:
  #   argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: apache
    server: https://kubernetes.default.svc
  project: default
  source:
    path: components/apache
    repoURL: https://github.com/moabukar/gitops-demo.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
