apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argo-cd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: platform
  source:
    path: components/ingress-nginx
    repoURL: https://github.com/moabukar/gitops-demo.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
